<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Shankar-PC" name="Test on Chrome" tests="12" failures="1" timestamp="9 Sep 2015 04:06:03 GMT" time="641.242" errors="0">
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="org.openqa.selenium.TimeoutException" message="timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=45.0.2454.85)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 600.04 seconds
Build info: version: &amp;apos;2.47.1&amp;apos;, revision: &amp;apos;unknown&amp;apos;, time: &amp;apos;2015-07-30 11:02:44&amp;apos;
System info: host: &amp;apos;Shankar-PC&amp;apos;, ip: &amp;apos;192.168.1.2&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_60&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\Shankar\AppData\Local\Temp\scoped_dir6952_9879}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.85, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 524cfa2941bb5ed21c4bff8bc5dbb634">
      <![CDATA[org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=45.0.2454.85)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 600.04 seconds
Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'Shankar-PC', ip: '192.168.1.2', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\Shankar\AppData\Local\Temp\scoped_dir6952_9879}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=45.0.2454.85, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 524cfa2941bb5ed21c4bff8bc5dbb634
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:306)
	at com.framework.testtemplate.TestBase.startWebDriver(TestBase.java:112)
	at com.framework.testtemplate.TestBase.beforeMethod(TestBase.java:77)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="com.rediff.testcases.ShoppingPageTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="@BeforeMethod LoginTestSetUp" time="0.0" classname="com.rediff.testcases.ShoppingPageTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod LoginTestSetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.rediff.testcases.ShoppingPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:150)
	at com.framework.testtemplate.TestBase.TearDown(TestBase.java:176)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="TestBrokenLink" time="1.635" classname="com.rediff.testcases.HomePageTest">
    <failure type="javax.net.ssl.SSLHandshakeException" message="sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target">
      <![CDATA[javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.net.HttpURLConnection.getResponseMessage(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseMessage(Unknown Source)
	at com.framework.actions.WebAction.getResponseCode(WebAction.java:423)
	at com.framework.actions.WebAction.isLinkBroken(WebAction.java:467)
	at com.rediff.pages.HomePage.verifyAllLinkOnHomePage(HomePage.java:81)
	at com.rediff.testcases.HomePageTest.TestBrokenLink(HomePageTest.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 41 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 47 more
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TestBrokenLink -->
  <testcase name="searchText" time="0.608" classname="com.rediff.testcases.HomePageTest"/>
  <testcase name="verifyUIElementsOnHomePage" time="0.373" classname="com.rediff.testcases.HomePageTest"/>
  <testcase name="invalidLoginTest" time="0.001" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="invalidLoginTest" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="invalidLoginTest" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="invalidLoginTest" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="invalidLoginTest" time="0.001" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="invalidLoginTest" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="invalidLoginTest" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="sucessfullLoginTest" time="0.0" classname="com.rediff.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- sucessfullLoginTest -->
  <testcase name="clickOnMenLifeStyleTest" time="0.001" classname="com.rediff.testcases.ShoppingPageTest">
    <skipped/>
  </testcase> <!-- clickOnMenLifeStyleTest -->
</testsuite> <!-- Test on Chrome -->
